# Generated by Django 4.2.4 on 2023-08-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rac',
            options={'verbose_name_plural': 'datos'},
        ),
    ]
